apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: lab
  name: ${{ values.app_name }}-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: ${{ values.app_name }}.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${{ values.app_name }}-svc
            port: 
              number: 8080